# Python
python.executable=C:/dev/workspace/risk-ai/pothole-check/venv/Scripts/python.exe
python.script=C:/dev/workspace/risk-ai/pothole-check/python/px-check.py
python.model=C:/dev/workspace/risk-ai/pothole-check/model/best.pt


# file upload (ex)
upload.basePath=src/main/webapp/upload/